// Render's monthly invoice — unlike Google's (lib/invoices/generate.ts),
// this can't be computed from synced data because Render exposes no cost
// API at all (see lib/providers/render/adapter.ts capabilities comment).
// The owner enters it once a month from Render's own closed-month Invoice
// History page, through /invoices/render/new — this just builds the PDF
// and upserts the row, same shape as Google's.

import { prisma } from '@/lib/db/prisma';
import { buildInvoicePdf } from './generate-pdf';

const ORGANIZATION_NAME = 'reshetimes-org';
// Render bills in USD regardless of the owner's own currency — shown as its
// own total, never blended into the Google/ILS numbers (spec §18 principle
// applied here too: no invented FX conversion).
const CURRENCY = 'USD';

export interface RenderInvoiceLineInput {
  name: string;
  amount: number;
}

export interface GenerateRenderInvoiceInput {
  periodStart: Date; // first of month, UTC
  periodEnd: Date; // last day of month, UTC
  lines: RenderInvoiceLineInput[];
}

export async function generateRenderInvoice(input: GenerateRenderInvoiceInput) {
  const totalAmount = input.lines.reduce((sum, l) => sum + l.amount, 0);
  const generatedAt = new Date();
  const periodLabel = `${String(input.periodStart.getUTCMonth() + 1).padStart(2, '0')}/${input.periodStart.getUTCFullYear()}`;

  const breakdown = [...input.lines].sort((a, b) => b.amount - a.amount).map((l) => ({ name: l.name, amount: l.amount }));

  const pdfLines = breakdown.map((l) => ({ title: l.name, amount: `${l.amount.toFixed(2)} ${CURRENCY}` }));

  // Prisma's generated Bytes type wants a Uint8Array<ArrayBuffer> —
  // Buffer.concat()'s result is typed as the wider Uint8Array<ArrayBufferLike>,
  // which TS strict mode rejects; a fresh copy settles the type.
  const pdfBytes = Uint8Array.from(
    await buildInvoicePdf({
      organizationName: ORGANIZATION_NAME,
      periodLabel,
      totalAmountLabel: `${totalAmount.toFixed(2)} ${CURRENCY}`,
      totalLabel: 'TOTAL FOR RENDER',
      generatedAtLabel: generatedAt.toLocaleString('en-GB', { timeZone: 'Asia/Jerusalem' }),
      sourceNote:
        "Internal PAY SCOPE summary — entered manually from Render's own closed-month Invoice History page. Render exposes no cost API (live or historical), so this isn't a synced number like the Google invoice above.",
      breakdownColumnLabel: 'SERVICE',
      lines: pdfLines,
    }),
  );

  const pdfFilename = `invoice-render-${ORGANIZATION_NAME}-${periodLabel.replace('/', '-')}.pdf`;

  return prisma.invoice.upsert({
    where: { provider_periodStart: { provider: 'RENDER', periodStart: input.periodStart } },
    create: {
      provider: 'RENDER',
      organizationName: ORGANIZATION_NAME,
      periodStart: input.periodStart,
      periodEnd: input.periodEnd,
      currency: CURRENCY,
      totalAmount,
      pdfBytes,
      pdfFilename,
      generatedAt,
      breakdownJson: breakdown,
    },
    update: {
      currency: CURRENCY,
      totalAmount,
      pdfBytes,
      pdfFilename,
      generatedAt,
      breakdownJson: breakdown,
    },
  });
}
