// Core logic for the monthly invoice summary (owner request — see the
// Invoice model comment in schema.prisma for why this exists instead of
// Google's own invoice PDF, and why it's one row per month org-wide rather
// than one row per billing account). Called from the internal cron
// endpoint, and safe to re-run for the same period — it upserts.

import { prisma } from '@/lib/db/prisma';
import { buildInvoicePdf } from './generate-pdf';
import { getConfiguredBillingAccountIds } from '@/lib/providers/google/config';

const ORGANIZATION_NAME = 'reshetimes-org';

export type GenerateInvoiceResult =
  | { status: 'generated'; invoiceId: string }
  | { status: 'skipped_no_cost_data' };

/**
 * The most recently *completed* calendar month — never the in-progress one,
 * since spend isn't final until the month ends (same principle as the MTD
 * forecast elsewhere: never present a partial number as if it were final).
 */
export function previousMonthRange(now: Date = new Date()): { start: Date; end: Date } {
  const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1));
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)); // exclusive
  return { start, end };
}

/** Friendly "BILLING N" labels, sorted alphabetically by the real ID for a
 * stable, deterministic numbering — same scheme as the dashboard's site
 * table, kept in sync manually since one is a DB read and the other reads
 * env config. */
function billingAccountLabel(id: string, allIds: string[]): string {
  const sorted = [...allIds].sort();
  return `BILLING ${sorted.indexOf(id) + 1}`;
}

export async function generateOrgInvoice(period: { start: Date; end: Date }): Promise<GenerateInvoiceResult> {
  const billingAccountIds = getConfiguredBillingAccountIds();
  if (billingAccountIds.length === 0) {
    return { status: 'skipped_no_cost_data' };
  }

  const accounts = await prisma.providerAccount.findMany({
    where: { externalAccountId: { in: billingAccountIds } },
  });
  const accountById = new Map(accounts.map((a) => [a.externalAccountId, a]));

  const perAccountTotals: { id: string; name: string; amount: number; currency: string }[] = [];
  for (const billingAccountId of billingAccountIds) {
    const account = accountById.get(billingAccountId);
    if (!account) continue; // not discovered yet — nothing to sum

    const rows = await prisma.costRecord.groupBy({
      by: ['currency'],
      where: { providerAccountId: account.id, usageDate: { gte: period.start, lt: period.end } },
      _sum: { netCost: true },
    });
    if (rows.length === 0) continue;

    // Spec §18 principle applied here too: never blend currencies into one
    // number. A single billing account bills in exactly one currency in
    // practice, so this picks whichever currency has the largest total for
    // that account.
    const dominant = rows.reduce((best, r) => (Number(r._sum.netCost ?? 0) > Number(best._sum.netCost ?? 0) ? r : best));
    perAccountTotals.push({
      id: billingAccountId,
      name: account.displayName,
      amount: Number(dominant._sum.netCost ?? 0),
      currency: dominant.currency,
    });
  }

  if (perAccountTotals.length === 0) {
    return { status: 'skipped_no_cost_data' };
  }

  // Same cross-account principle: sum only the accounts sharing the
  // dominant currency into the headline total; an account billing in a
  // different currency still appears in the breakdown table, just not
  // folded into totalAmount.
  const totalsByCurrency = new Map<string, number>();
  for (const a of perAccountTotals) {
    totalsByCurrency.set(a.currency, (totalsByCurrency.get(a.currency) ?? 0) + a.amount);
  }
  const [currency, totalAmount] = [...totalsByCurrency.entries()].sort((a, b) => b[1] - a[1])[0]!;

  const breakdown = perAccountTotals
    .sort((a, b) => b.amount - a.amount)
    .map((a) => ({
      billingAccountId: a.id,
      billingAccountName: a.name,
      amount: a.amount,
      currency: a.currency,
    }));

  const generatedAt = new Date();
  const periodLabel = `${String(period.start.getUTCMonth() + 1).padStart(2, '0')}/${period.start.getUTCFullYear()}`;

  const pdfLines = breakdown.map((b) => ({
    title: `${billingAccountLabel(b.billingAccountId, billingAccountIds)} — ${b.billingAccountName}`,
    subtitle: b.billingAccountId,
    amount: `${b.amount.toFixed(2)} ${b.currency}`,
  }));

  // Prisma's generated Bytes type wants a Uint8Array<ArrayBuffer> —
  // Buffer.concat()'s result is typed as the wider Uint8Array<ArrayBufferLike>,
  // which TS strict mode rejects; a fresh copy settles the type.
  const pdfBytes = Uint8Array.from(
    await buildInvoicePdf({
      organizationName: ORGANIZATION_NAME,
      periodLabel,
      totalAmountLabel: `${totalAmount.toFixed(2)} ${currency}`,
      totalLabel: 'TOTAL FOR ORGANIZATION',
      generatedAtLabel: generatedAt.toLocaleString('en-GB', { timeZone: 'Asia/Jerusalem' }),
      sourceNote:
        "Internal PAY SCOPE summary built from cost data synced from Google Cloud Billing — not Google's official tax invoice (Google exposes no API for that; only a manual Console download).",
      breakdownColumnLabel: 'BILLING ACCOUNT',
      lines: pdfLines,
    }),
  );

  const pdfFilename = `invoice-google-${ORGANIZATION_NAME}-${periodLabel.replace('/', '-')}.pdf`;

  const invoice = await prisma.invoice.upsert({
    where: { provider_periodStart: { provider: 'GOOGLE_CLOUD', periodStart: period.start } },
    create: {
      provider: 'GOOGLE_CLOUD',
      organizationName: ORGANIZATION_NAME,
      periodStart: period.start,
      periodEnd: new Date(period.end.getTime() - 1),
      currency,
      totalAmount,
      pdfBytes,
      pdfFilename,
      generatedAt,
      breakdownJson: breakdown,
    },
    update: {
      currency,
      totalAmount,
      pdfBytes,
      pdfFilename,
      generatedAt,
      breakdownJson: breakdown,
    },
  });

  return { status: 'generated', invoiceId: invoice.id };
}
